### ISSUE TITLE
When adding more than one instance at time via clone-instance the hostname increment

### ISSUE THREAD

**Issue by anfleene** [sportngin/opsicle#113]
The first server you add increments the hostname properly, the second server tries to use the same hostname, you have to override it to get it to work.

**Comment by chrisarcand** [comment]
💩 

(btw I'm sad that the reactions feature doesn't allow 💩)

**Comment by emmasax1** [comment]
This has now been fixed in https://github.com/sportngin/opsicle/pull/121.
