### ISSUE TITLE
deploy and execute-recipes fail without a TTY

### ISSUE THREAD

**Issue by bbergstrom** [sportngin/opsicle#77]
When executed without a terminal/tty, like from a cron or `at`, the commands fail because the monitor expects a TTY.
```
executing [/usr/local/bin/opsicle deploy -t $SOYUZ_ENVIRONMENT]...
Error opening terminal: unknown.
error: exit
```

These commands should work with TTY or not so opsicle can be used non interactively.

**Comment by ChrisArcand** [comment]
Arguably the problem is the constant issue of having the monitor to handle queueing on OpsWorks :disappointed: Preferably you wouldn't even be running the monitor for cron jobs with `--no-monitor`. 

Sadly that would take a _lot_ of work, so a quick patch for the TTY makes sense for now. :ok_hand:

**Comment by bbergstrom** [comment]
Fixed by https://github.com/sportngin/opsicle/pull/78
