### ISSUE TITLE
Possible to relax Nokogiri version constraint?

### ISSUE THREAD

**Issue by pbyrne** [sportngin/opsicle#80]
I see that https://github.com/sportngin/opsicle/commit/1eb4b93dc8c3db37a029a64338119a4908ea2bc5 locked Nokogiri to `'~> 1.6.3.1'`, presumably because of some problem with the then-current 1.6.4 or 1.6.4.1, but this isn't specified. Nokogiri is now up to 1.6.6.2, presumably with interesting bug fixes and performance improvements. Is it possible to relax the Nokogiri version constraint now?

For what it's worth, our app was successfully using Nokogiri 1.6.6.2 and opsicle 0.8.0 (which didn't have that version constraint) with no problems.

**Comment by NickLaMuro** [comment]
From what I recall, it was probably an issue with OSX and our use with brew-gem.  I would have to do some more digging to tell you for sure.

**Comment by anfleene** [comment]
iirc both of you are right.  they've probably fixed it by now so we can likely relax that.
