### ISSUE TITLE
Having an MFA token in ~/.fog causes soyuz deploys to fail

### ISSUE THREAD

**Issue by matthewrkrieger** [sportngin/opsicle#82]
Output of the issue is listed below. Removing mfa_serial_number from ~/.fog fixed the issue.  
  
Oddly enough the deploy actually succeeded despite the error returned to the terminal. 
```
[~/sportngin/ngin] (staging.2015.05.12)$ soyuz deploy
Choose an Environment:
1) staging
2) production
? 1
1) Don't Expire CSS
2) Expire CSS
? 1
executing [echo not expiring css]...
not expiring css
1) Without After Deploy Migrations
2) With After Deploy Migrations
? 1
1) Deploy
2) Deploy with Migrations
? 1
executing [/usr/local/bin/opsicle deploy -t $SOYUZ_ENVIRONMENT]...
Enter MFA token: 136921
Starting OpsWorks deploy...
Enter MFA token: 136921
error: The security token included in the request is invalid
error: exit
[~/sportngin/ngin] (staging.2015.05.12)$
```

It is also worth noting that ```opsicle monitor staging``` also prompted for the MFA token and worked as expected.

**Comment by anfleene** [comment]
@bbergstrom iirc you added the MFA support right?

**Comment by bbergstrom** [comment]
Yes.  The AWS account you are making API calls to with opsicle doesn't require MFA.  Maybe that case isn't being handled correctly.

**Comment by bbergstrom** [comment]
The opsicle deploy does two API calls, the create deployment call and the tracking monitor calls.  The deploy is successful, but the monitor calls appear to be invalid.  Digging...
