### ISSUE TITLE
Switch aws credential management to use the AWS SDK's `.aws/credentials` file

### ISSUE THREAD

**Issue by anfleene** [sportngin/opsicle#88]
The `~/.fog` file really doesn't make sense since we don't depend on fog. Lets switch to using the aws recommended usage of `~/.aws/credentials` profiles

We should also include some sort of transition detection that offers to setup a profile for you if you don't have one but have a fog profile that matches.

**Comment by emmasax1** [comment]
Fixed with https://github.com/sportngin/opsicle/pull/100
